# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  飞行器的执行周期
subtitle: 点滴积累，贵在坚持
name: 飞行器的执行周期 
email: 871281347@qq.com
description: 本站是纯洁的微笑的技术分享博客。内容涵盖生活故事、Java后端技术、Spring Boot、Spring Cloud、微服务架构、大数据演进、高可用架构、中间件使用、系统监控等相关的研究与知识分享。
keywords: 李雪腾,飞行器的执行周期,Spring,Spring Boot,Spring Cloud,MongoDB,Jvm,Docker,生活故事,架构,大数据,一线,FastDFS,开发者,编程,代码,开源,IT网站,Developer,Programmer,Coder,Geek,IT技术博客,Java,Python,
encoding: "utf-8"
favicon: favicon.ico 

repository: Leexxttt/Leexxttt.github.io
github_url: https://github.com/Leexxttt
url: http://blog.lixueteng.top
enforce_ssl: blog.lixueteng.top

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /gitchat.html
    label: JVM
    target: _self

  -
    href: /geektime.html
    label: 算法4
    target: _self

  -
    href: /life.html
    label: 故事
    target: _self

  -
    href: /arch.html
    label: 网络
    target: _self

  -
    href: /link.html
    label: 集合
    target: _self



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  - 
    href: /java.html
    label: Java
    target: _self

  -
    href: /archives.html
    label: Archives
    target: _self

  -
    href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  -
    href: /payment.html
    label: 支付     
    target: _self

  -
    href: /fastdfs.html
    label: MySQL
    target: _blank

  -
    href: /mongodb.html
    label: 剑指offer
    target: _blank

  -
    href: /docker.html
    label: Docker
    target: _blank




# selected articles
classes:

  -
    href: /datastructure.html
    name: 数据结构与算法
    describe: 数据是骨肉，算法是灵魂

  -
    href: /spring.html
    name: Spring源码解析
    describe: java coder必知必会

  -
    href: /java.html
    name: Java 系列文章
    describe: 夯实基础，砥砺前行


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]

comments_provider: gitalk
gitalk:
    owner: lixt
    repo: Leexxttt.github.io
    clientID: 1d555855a616dc57f615
    clientSecret: e784fd0bf61788dfb7d342dc40280db7a4a79dd1

